config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  resources :recipe_foods
  root 'foods#index'

  devise_for :users
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  
  # resources :foods, only: [:new, :edit, :update, :show, :destory]
  
  resources :foods, only: [:index, :new, :create, :show, :destroy]
  resources :public_recipes, only: [:index]
  
  resources :users, only: [:index, :show]

  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    resources :shopping_lists, only: [:index]
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :destroy

  validates :name, presence: true
  validates :cooking_time, presence: true
  validates :preparation_time, presence: true
  validates :description, presence: true

  def total_price
    recipe_foods.sum { |item| item.quantity * item.food.price }
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  def index
    @recipes = current_user.recipes.includes(:user)
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = @recipe.recipe_foods.includes([:food])
  end

  def new
    @recipe = Recipe.new
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "contents") do |form| %>
    <% if recipe.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
  
        <ul>
          <% recipe.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="my-5">
      <%= form.label :name %>
      <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  
    <div class="my-5">
      <%= form.label :preparation_time %>
      <%= form.number_field :preparation_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  
    <div class="my-5">
      <%= form.label :cooking_time %>
      <%= form.number_field :cooking_time, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  
    <div class="my-5">
      <%= form.label :description %>
      <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  
    <div class="my-5">
      <%= form.label :public %>
      <%= form.text_field :public, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  
    <div class="my-5">
      <%= form.label :user_id %>
      <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>
  
    <div class="inline">
      <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    </div>
  <% end %>
  

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>" class="w-[90%] mx-auto border-gray-900 border-4 my-3 rounded-sm cursor-pointer">
<%= link_to "", recipe, class: "ml-24 w-[69%] p-16 flex justify-center absolute " %>
     <div class="flex justify-between p-4">
          <p class="my-2 text-2xl z-10">
        <%= recipe.name %>
      </p>

      <p class="my-2 w-[50%]">
        <%= recipe.description %>
      </p>
     </div>
      <div class="rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer m-2 underline text-xl">
      <%= button_to "Delete", recipe_path(recipe.id ), :method => :delete %> 
      </div>
</div>

app/views/recipes/_recipe_details.html.erb
<div id="<%= dom_id recipe %>" class="w-[70%] mx-auto border-gray-900 border-4 my-3 rounded-sm cursor-pointer">
<%= link_to "", recipe, class: " w-[69%] p-16 flex justify-center absolute " %>
     <div class="flex justify-between p-4">
          <p class="my-2 text-2xl z-10">
        <%= recipe.name %>
      </p>
      <p class="my-5">
    <strong class="block font-medium mb-1">Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= recipe.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Public:</strong>
    <%= recipe.public %>
  </p>

      <p class="my-2">
        <%= recipe.description %>
      </p>
     </div>
      <div class="rounded-lg py-2 px-4 bg-blue-600 text-white inline-block font-medium cursor-pointer m-2 underline text-xl">
      <%= button_to 'REMOVE', method: :delete%>
      </div>
</div>

app/views/recipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing recipe</h1>

  <%= render "form", recipe: @recipe %>
  <%= link_to "Show this recipe", @recipe, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to recipes", recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/index.html.erb
<div class="w-full mt-2">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center m-4">
  <h1 class="font-bold text-4xl ml-4">Recipes</h1>
  <%= link_to 'Add New recipe', new_recipe_path, class: "rounded-lg py-3 px-5 mr-4 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="recipes" class="min-w-full">
    <%= render @recipes %>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New recipe</h1>

  <%= render "form", recipe: @recipe %>
  <%= link_to 'Back to recipes', recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/show.html.erb
<div class="mx-auto  w-[70%]">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <div id="<%= dom_id @recipe %>">
    <p class="my-5 text-center text-3xl font-bold">
      <%= @recipe.name %>
    </p>
  
    <p class="my-5">
      <strong class="font-bold mb-1">Preparation time:</strong>
      <%= @recipe.preparation_time %>
      <span class="float-right">Public</span>
    </p>
  
    <p class="my-5">
      <strong class="font-medium mb-1">Cooking time:</strong>
      <%= @recipe.cooking_time %>
    </p>
    <p class="font-bold py-2">Steps go here...</p>  
    </div>

    <div class="flex justify-between p-2 text-xl">
    <div class="border-gray-900 p-2 border-4 my-3 rounded-sm">
          <%= link_to 'Genarate shopping list', class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <div class="border-gray-900 p-2 border-4 my-3 rounded-sm">
    <%= link_to 'Add ingredient', new_recipe_recipe_food_path(:recipe_id => @recipe.id)%>
    </div>
  </div>
  <%= render "shared/show_recipe", recipe: @recipe%>
</div>