config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  resources :recipe_foods
  root 'foods#index'

  devise_for :users
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  
  # resources :foods, only: [:new, :edit, :update, :show, :destory]
  
  resources :foods, only: [:index, :new, :create, :show, :destroy]
  resources :public_recipes, only: [:index]
  
  resources :users, only: [:index, :show]

  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    resources :shopping_lists, only: [:index]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, foreign_key: :user_id, dependent: :destroy
  has_many :foods, foreign_key: 'user_id', dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4">
  <div class="container-fluid d-flex">
  <%= link_to 'Recipe App', root_path, class: 'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Foods', foods_path, class: 'nav-link'%>
        </li>
         <li class="nav-item">
        <%= link_to 'Recipes', recipes_path, class: 'nav-link'%>
        </li>
        <li><%= link_to "Public Recipes", public_recipes_path, class: "text-decoration-none nav-link"%></li>
        <%# <li class='nav-link'>Shopping List</li> %>
        <% if current_user %>
          <li class='nav-link text-white'><%= current_user.name %></li>
        <% end %>
        <li class="d-flex ml-auto mb-3 mt-2">
          <% if user_signed_in? %>
            <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-warning  text-end sign', data: { turbo: false } %>
          <% else %>
            <%= button_to 'Sign In', new_user_session_path, class: 'btn btn-warning  text-end sign'%>
          <% end%>
        </li>
      </ul>
        
    </div>
  </div>
</nav>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>
<div id="users">
  <h2><%= 'Foods' %></h2>
</div>

<%# <%= link_to "New user", new_user_session_path %> 