config/routes.rb
Rails.application.routes.draw do
  get 'shopping_lists/index'
  resources :recipe_foods
  root 'foods#index'

  devise_for :users
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users
  
  # resources :foods, only: [:new, :edit, :update, :show, :destory]
  
  resources :foods, only: [:index, :new, :create, :show, :destroy]
  resources :public_recipes, only: [:index]
  
  resources :users, only: [:index, :show]

  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
    resources :shopping_lists, only: [:index]
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :recipes, through: :recipe_foods

  validates :name, presence: true, length: { in: 1..50 }
  validates :measurement_unit, presence: true, length: { in: 1..20 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def edit
    @food = Food.find(params[:id])
  end

  def show
    @food = Food.find(params[:id])
  end

  # POST /foods or /foods.json
  def create
    @food = current_user.foods.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
      else
        flash[:alert] = 'Oops, Loser try again!'
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    food = Food.find(params[:id])
    respond_to do |format|
      if food.destroy
        format.html { redirect_to foods_path, notice: 'Food was deleted successfully.' }
      else
        format.html { render :new, alert: 'An error has occurred while deleting food, try again' }
      end
    end
  end

  private

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>" class="d-flex justify-content-between fooods">
  <p>
    <%= food.name %>
  </p>

  <p>
    <%= food.quantity %>
  </p>

  <p>
    <%= food.measurement_unit %>
  </p>

  <p>
    $<%= food.price %>
  </p>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food ) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red", class="field mb-3">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :measurement_unit, style: "display: block" %>
    <%= form.text_field :measurement_unit, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, class: "form-control" %>
  </div>

  <div class="field mb-3">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class: "form-control" %>
  </div>

  <div class="btn mb-3 p-0">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<div class="container rounded-top mb-4">
  <div class="container d-flex gap-5 align-items-center">
    <h1>Hey, <%= current_user.name %><span>&#x1F468;&#x200D;&#x1F373;</span>&nbsp;&nbsp;&nbsp;<i class="fa fa-hand-o-right"></i></h1>

    <div class="ms-auto m-1">
      <%= link_to "Add New food", new_food_path, class: "btn btn-warning mt-10 mb-10 text-end m-3 me-auto order-last" %>
    </div>
  </div>

  <div class='shadow-lg p-3 bg-body-tertiary'>
    <div class="d-flex justify-content-between fooods_title">
      <h5>
        Food
      </h5>
      <h5>
        Quantity
      </h5>
      <h5>
        Measurement unit
      </h5>
      <h5>
        Unit price
      </h5>
      <h5>
        Actions
      </h5>
    </div>
  </div>

  <% @foods.each do |food| %>
    <div class='shadow-lg p-3 bg-body-tertiary'>
      <div class="d-flex align-items-center">
        <%= render food %>
        <h3><%= button_to "Delete", food, method: :delete,  class: 'btn btn-warning m-2 text-end delete', data: { turbo: false }  %></h3>
      </div>
    </div>
  <% end %>
</div>

app/views/foods/new.html.erb
<div class="container bg-warning">
  <div class="d-flex align-items-center">
    <h1>New food</h1>
    <div class="ms-auto m-3">
      <%= link_to "Back to foods", foods_path, class: "btn btn-dark mt-10 mb-10 text-decoration-none" %>
    </div>
  </div>
  <%= render "form", food: @food %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div class="container bg-warning rounded-top">
  <div class="d-flex">
    <div>
      <%= link_to "Back to foods", foods_path, class: "btn btn-secondary m-2 mb-10 text-decoration-none" %>
    </div>
    <div class="ms-auto m-1 order-last">
      <h3><%= button_to "Delete", food_path(@food.id), method: :delete,  class: 'btn btn-secondary', data: { turbo: false }  %></h3>
    </div>
  </div>
</div>